@startuml Architecture Metamodel
!$subdomain = "rectangle"
'
!$context = "card"
'
!$microservice="agent"
'
!$function="storage"
'
!$azure_service="cloud"
'
!$device="actor"
'
!$topic="interface"
'
!unquoted procedure $updates($subject, $object)
$subject --> $object
!endprocedure
'
!unquoted procedure $exposes_topic($subject, $topic_name, $id)
$topic "$topic_name" as $id
$subject -- $id
!endprocedure
'
!unquoted procedure $observes($subject, $object)
$subject --( $object
!endprocedure
'
!unquoted procedure $sends_commands($subject, $object)
$subject ..> $object
!endprocedure
'
@enduml
