@startuml Domain Entities Metamodel
!unquoted function $as_alias($name="")
!if ($name == "")
    !return ""
!else
    !return "as $name"
!endif
!endfunction
'
!unquoted procedure $service($name, $alias="")
class "$name" $as_alias($alias) << Domain Service >>
!endprocedure
skinparam spotChar<<Domain Service>> S
skinparam stereotypeC<<Domain Service>> {
  BackgroundColor #FCEC03
}
'
!unquoted procedure $factory($name, $alias="")
class "$name" $as_alias($alias) << Factory >>
!endprocedure
skinparam spotChar<<Factory>> F
skinparam stereotypeC<<Factory>> {
  BackgroundColor #FCEC03
}
'
!unquoted procedure $entity($name, $alias="")
entity "$name" $as_alias($alias) << Entity >>
!endprocedure
'
!unquoted procedure $aggregate_root($name, $alias="")
class "$name" $as_alias($alias) << Aggregate Root >>
!endprocedure
skinparam spotChar<<Aggregate Root>> R
skinparam stereotypeC<<Aggregate Root>> {
  BackgroundColor #FCEC03
}
'
!unquoted procedure $value($name, $alias="")
class "$name" $as_alias($alias) << ValueObject >>
!endprocedure
skinparam spotChar<<ValueObject>> V
skinparam stereotypeC<<ValueObject>> {
  BackgroundColor #FCEC03
}
'
!unquoted procedure $aggregate($name)
rectangle "$name Aggregate"
!endprocedure
'
!unquoted procedure $enum($name)
enum "$name" << Enum >>
!endprocedure
@enduml