@startuml Domain Entities Metamodel
!unquoted procedure $service($name)
class "$name" << Domain Service >>
!endprocedure
!unquoted procedure $service($name, $alias)
class "$name" as $alias << Domain Service >>
!endprocedure
!unquoted procedure $factory($name)
class "$name" << Factory >>
!endprocedure
!unquoted procedure $factory($name, $alias)
class "$name" as $alias << Factory >>
!endprocedure
!$entity="entity"
!$value="class"
!$enum="enum"
@enduml