@startuml Use Case Diagram
left to right direction
actor "Customer" as c
actor "Manager" as m
actor "Assistant" as a
rectangle "Use Cases" {
    usecase "Rent" as rent
    usecase "Pay" as pay
    usecase "Search scooters" as search 
    usecase "Ring scooter" as ring
    usecase "Unlock scooter" as unlock
    usecase "Start trip" as start_trip
    usecase "Confirm trip end" as confirm_end
    usecase "End trip" as end_trip
    usecase "Exit Area of Service" as exit_area
    usecase "Ride the scooter" as ride
    usecase "Ride the scooter until battery runs out" as ride_lot
    usecase "Receive low battery notification" as battery_notification
    usecase "Receive out of service area notification" as area_notification
    usecase "Monitor all scooters in the map" as monitor
    usecase "See suggested drop points" as see_points

    confirm_end .down.> end_trip : <<include>>
    exit_area .down.> end_trip : <<include>>
    exit_area .down.> area_notification : <<include>>
    ride_lot .up.> ride : <<extend>>
    ride_lot .up.> end_trip : <<include>>
    rent .down.> start_trip : <<include>>
    rent .down.> end_trip : <<include>>
    rent .> pay : <<include>>
    ride_lot .> battery_notification : <<include>>
}
c -- search
c -- ring
c -- rent
c -- confirm_end
c -- exit_area
c -- ride

m -- monitor
m -- see_points

a -- monitor
a -- see_points
a -- unlock
@enduml